baseURL = "https://leroyer.io/"
languageCode = "en-us"
title = "leroyer.io"
theme = "risotto"
paginate = 3
DefaultContentLanguage = "en"
enableInlineShortcodes = true
# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]

# Automatically add content sections to main menu
sectionPagesMenu = "main"
author = "Antoine Leroyer"

[params]
  noindex = false

# [params.style]
#   darkestColor = "#23232d"
#   darkColor = "#121216"
#   lightColor = "#f5e3e0"
#   lightestColor = "#007feb"
#   primaryColor = "#fff"

[params.theme]
palette = "github"

# Sidebar: about/bio
[params.about]
title = "Antoine Leroyer"
description = "Hi. I'm Antoine, an Infrastructure Engineer and SRE. Currently working at Deezer."
logo = "avatar.png"

# Sidebar: social links
# Available icon sets:
# * FontAwesome 6 <https://fontawesome.com/> ('fa-brands', 'fa-normal', or 'fa-solid' for brands)
# * Academicons <https://jpswalsh.github.io/academicons> ('ai ai-')

[[params.socialLinks]]
icon = "fa-brands fa-github"
title = "GitHub"
url = "https://github.com/aleroyer"

[[params.socialLinks]]
icon = "fa-brands fa-linkedin"
title = "LinkedIn"
url = "https://www.linkedin.com/in/antoineleroyer/"

[[params.socialLinks]]
icon = "fa-solid fa-comment"
title = "Matrix"
url = "https://matrix.to/#/@aleroyer:matrix.org"

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

# For hugo >= 0.60.0, enable inline HTML
[markup.goldmark.renderer]
unsafe = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true
