baseURL = "https://leroyer.io/"
languageCode = "en-us"
title = "Leroyer I/O"
theme = "m10c"

[params]
  author = "Antoine Leroyer"
  description = "Hi. I'm Antoine, an Infrastructure Engineer and SRE. Currently working at Deezer."
  avatar = "avatar.png"
  [[params.social]]
    name = "github"
    url = "https://github.com/aleroyer"

[params.style]
  darkestColor = "#23232d"
  darkColor = "#121216"
  lightColor = "#f5e3e0"
  lightestColor = "#007feb"
  primaryColor = "#fff"
